services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000" # Mapea el puerto 3000 del host al puerto 3000 del contenedor
    restart: unless-stopped